name: hfradarpy
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.10
  - xarray
  - netcdf4
  - pyproj
  - joblib
  - click
  - bottleneck
  - dask
  - geopandas
  - cartopy
  - matplotlib
  - cmocean
  - jupyterlab
  - nb_conda_kernels
  - basemap
  - geopy
  - oceans
  - pytest